// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reviews;

#nullable disable

namespace Reviews.Migrations
{
    [DbContext(typeof(AppReviewsDbContext))]
    [Migration("20260826200810_AddReviewsModule")]
    partial class AddReviewsModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reviews.Entities.GuestReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("guest_email");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int>("OverallRating")
                        .HasColumnType("integer")
                        .HasColumnName("overall_rating");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_guest_reviews");

                    b.HasIndex(new[] { "BookingId" }, "ix_guest_reviews_booking_id")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_reviews_booking_id");

                    b.HasIndex(new[] { "HostId" }, "ix_guest_reviews_host_id")
                        .HasDatabaseName("ix_guest_reviews_host_id");

                    b.ToTable("guest_reviews", (string)null);
                });

            modelBuilder.Entity("Reviews.Entities.StayReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccuracyRating")
                        .HasColumnType("integer")
                        .HasColumnName("accuracy_rating");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<int>("CleanlinessRating")
                        .HasColumnType("integer")
                        .HasColumnName("cleanliness_rating");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("CommunicationRating")
                        .HasColumnType("integer")
                        .HasColumnName("communication_rating");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<DateTimeOffset?>("HostRepliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("host_replied_at");

                    b.Property<string>("HostReplyText")
                        .HasColumnType("text")
                        .HasColumnName("host_reply_text");

                    b.Property<int>("LocationRating")
                        .HasColumnType("integer")
                        .HasColumnName("location_rating");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<decimal>("OverallRating")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("overall_rating");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid?>("ReviewerCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_customer_id");

                    b.Property<string>("ReviewerGuestEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("reviewer_guest_email");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("ValueRating")
                        .HasColumnType("integer")
                        .HasColumnName("value_rating");

                    b.HasKey("Id")
                        .HasName("pk_stay_reviews");

                    b.HasIndex(new[] { "BookingId" }, "ix_stay_reviews_booking_id")
                        .IsUnique()
                        .HasDatabaseName("ix_stay_reviews_booking_id");

                    b.HasIndex(new[] { "HostId" }, "ix_stay_reviews_host_id")
                        .HasDatabaseName("ix_stay_reviews_host_id");

                    b.HasIndex(new[] { "PropertyId" }, "ix_stay_reviews_property_id")
                        .HasDatabaseName("ix_stay_reviews_property_id");

                    b.ToTable("stay_reviews", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
