<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper"/>
        <PackageReference Include="Dapper.AOT"/>
        <PackageReference Include="EFCore.NamingConventions"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Core\SeedWork\SeedWork.csproj"/>
        <ProjectReference Include="..\..\Core\BuildingBlocks\BuildingBlocks.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="JetBrains.Annotations">
        <HintPath>C:\Users\Zephyrus\.nuget\packages\jetbrains.annotations\2026.2.0\lib\netstandard2.0\JetBrains.Annotations.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
