// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Persistence;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bookings.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("booking_status");

                    b.Property<string>("CancellationPolicy")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cancellation_policy");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date")
                        .HasColumnName("check_in");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date")
                        .HasColumnName("check_out");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("guest_email");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("guest_name");

                    b.Property<string>("GuestPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("guest_phone");

                    b.Property<Guid>("HoldId")
                        .HasColumnType("uuid")
                        .HasColumnName("hold_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<DateTimeOffset?>("PaymentDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_due_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<decimal>("_subtotal")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("subtotal");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPrice", "Bookings.Entities.Booking.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("total_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_bookings_customer_id");

                    b.HasIndex("HoldId")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_hold_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_bookings_unit_id");

                    b.HasIndex(new[] { "PaymentDueAt" }, "ix_bookings_payment_due_at_pending")
                        .HasDatabaseName("ix_bookings_payment_due_at")
                        .HasFilter("booking_status = 'Pending' AND payment_due_at IS NOT NULL");

                    b.ToTable("bookings", "bookings");
                });

            modelBuilder.Entity("Bookings.Entities.BookingManagementToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_booking_management_tokens");

                    b.HasIndex(new[] { "BookingId" }, "ix_booking_management_tokens_booking_id")
                        .HasDatabaseName("ix_booking_management_tokens_booking_id");

                    b.HasIndex(new[] { "TokenHash" }, "ix_booking_management_tokens_token_hash")
                        .IsUnique()
                        .HasDatabaseName("ix_booking_management_tokens_token_hash");

                    b.ToTable("booking_management_tokens", "bookings");
                });

            modelBuilder.Entity("Bookings.Entities.CheckoutIdempotencyRecord", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("key_hash");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("request_fingerprint");

                    b.HasKey("BookingId")
                        .HasName("pk_checkout_idempotency_records");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_checkout_idempotency_created_at")
                        .HasDatabaseName("ix_checkout_idempotency_created_at");

                    b.HasIndex(new[] { "KeyHash" }, "ix_checkout_idempotency_key_hash")
                        .IsUnique()
                        .HasDatabaseName("ix_checkout_idempotency_key_hash");

                    b.ToTable("checkout_idempotency_records", "bookings");
                });

            modelBuilder.Entity("Bookings.Entities.RefundObligation", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cause");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<decimal>("PolicyRefundAmount")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("policy_refund_amount");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("BookingId")
                        .HasName("pk_refund_obligations");

                    b.HasIndex(new[] { "NextAttemptAt" }, "ix_refund_obligations_unresolved")
                        .HasDatabaseName("ix_refund_obligations_unresolved")
                        .HasFilter("resolved_at IS NULL");

                    b.ToTable("refund_obligations", "bookings");
                });

            modelBuilder.Entity("Bookings.Entities.UnitAvailabilityHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BookedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at");

                    b.Property<string>("ClientKey")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("client_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<DateTimeOffset?>("HoldExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hold_expires_at");

                    b.Property<decimal?>("LengthOfStayDiscountAmount")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("length_of_stay_discount_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<NpgsqlRange<DateOnly>>("StayRange")
                        .HasColumnType("daterange")
                        .HasColumnName("stay_range");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPrice", "Bookings.Entities.UnitAvailabilityHold.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("total_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_unit_availability_holds");

                    b.HasIndex("HoldExpiresAt")
                        .HasDatabaseName("ix_unit_availability_holds_hold_expires_at")
                        .HasFilter("status = 'held'");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_unit_availability_holds_unit_id");

                    b.HasIndex(new[] { "ClientKey" }, "ix_unit_availability_holds_client_key_active")
                        .HasDatabaseName("ix_unit_availability_holds_client_key_active")
                        .HasFilter("status IN ('held', 'pending_payment')");

                    b.ToTable("unit_availability_holds", "bookings");
                });

            modelBuilder.Entity("Catalog.Entities.PricingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<NpgsqlRange<DateOnly>?>("DateRange")
                        .HasColumnType("daterange")
                        .HasColumnName("date_range");

                    b.PrimitiveCollection<int[]>("DaysOfWeek")
                        .HasColumnType("integer[]")
                        .HasColumnName("days_of_week");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_percent");

                    b.Property<int?>("MinNights")
                        .HasColumnType("integer")
                        .HasColumnName("min_nights");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<decimal?>("Multiplier")
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("multiplier");

                    b.Property<decimal?>("OverridePrice")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("override_price");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rule_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_pricing_rules");

                    b.HasIndex(new[] { "UnitId" }, "ix_pricing_rules_unit_day_of_week_0_active")
                        .IsUnique()
                        .HasDatabaseName("ix_pricing_rules_unit_day_of_week_0_active")
                        .HasFilter("rule_type = 'DayOfWeekMultiplier' AND status <> 2 AND days_of_week @> ARRAY[0]");

                    b.HasIndex(new[] { "UnitId" }, "ix_pricing_rules_unit_day_of_week_1_active")
                        .IsUnique()
                        .HasDatabaseName("ix_pricing_rules_unit_day_of_week_1_active")
                        .HasFilter("rule_type = 'DayOfWeekMultiplier' AND status <> 2 AND days_of_week @> ARRAY[1]");

                    b.HasIndex(new[] { "UnitId" }, "ix_pricing_rules_unit_day_of_week_2_active")
                        .IsUnique()
                        .HasDatabaseName("ix_pricing_rules_unit_day_of_week_2_active")
                        .HasFilter("rule_type = 'DayOfWeekMultiplier' AND status <> 2 AND days_of_week @> ARRAY[2]");

                    b.HasIndex(new[] { "UnitId" }, "ix_pricing_rules_unit_day_of_week_3_active")
                        .IsUnique()
                        .HasDatabaseName("ix_pricing_rules_unit_day_of_week_3_active")
                        .HasFilter("rule_type = 'DayOfWeekMultiplier' AND status <> 2 AND days_of_week @> ARRAY[3]");

                    b.HasIndex(new[] { "UnitId" }, "ix_pricing_rules_unit_day_of_week_4_active")
                        .IsUnique()
                        .HasDatabaseName("ix_pricing_rules_unit_day_of_week_4_active")
                        .HasFilter("rule_type = 'DayOfWeekMultiplier' AND status <> 2 AND days_of_week @> ARRAY[4]");

                    b.HasIndex(new[] { "UnitId" }, "ix_pricing_rules_unit_day_of_week_5_active")
                        .IsUnique()
                        .HasDatabaseName("ix_pricing_rules_unit_day_of_week_5_active")
                        .HasFilter("rule_type = 'DayOfWeekMultiplier' AND status <> 2 AND days_of_week @> ARRAY[5]");

                    b.HasIndex(new[] { "UnitId" }, "ix_pricing_rules_unit_day_of_week_6_active")
                        .IsUnique()
                        .HasDatabaseName("ix_pricing_rules_unit_day_of_week_6_active")
                        .HasFilter("rule_type = 'DayOfWeekMultiplier' AND status <> 2 AND days_of_week @> ARRAY[6]");

                    b.HasIndex(new[] { "UnitId" }, "ix_pricing_rules_unit_length_of_stay_active")
                        .IsUnique()
                        .HasDatabaseName("ix_pricing_rules_unit_length_of_stay_active")
                        .HasFilter("rule_type = 'LengthOfStayDiscount' AND status <> 2");

                    b.HasIndex(new[] { "UnitId", "RuleType" }, "ix_pricing_rules_unit_type")
                        .HasDatabaseName("ix_pricing_rules_unit_type");

                    b.ToTable("pricing_rules", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_pricing_rules_days_of_week_domain", "rule_type <> 'DayOfWeekMultiplier' OR (cardinality(days_of_week) > 0 AND days_of_week <@ ARRAY[0,1,2,3,4,5,6])");
                        });
                });

            modelBuilder.Entity("Catalog.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("property_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_properties");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_properties_host_id");

                    b.HasIndex(new[] { "City" }, "ix_properties_city_trgm")
                        .HasDatabaseName("ix_properties_city_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "City" }, "ix_properties_city_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "City" }, "ix_properties_city_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("properties", "catalog");
                });

            modelBuilder.Entity("Catalog.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationPolicy")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cancellation_policy");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("integer")
                        .HasColumnName("max_occupancy");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BasePrice", "Catalog.Entities.Unit.BasePrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("base_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("PropertyId")
                        .HasDatabaseName("ix_units_property_id");

                    b.ToTable("units", "catalog");
                });

            modelBuilder.Entity("Hosts.Entities.Host", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("business_name");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .HasColumnType("jsonb")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_hosts");

                    b.ToTable("hosts", "hosts");
                });

            modelBuilder.Entity("Identity.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Identity.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<Guid?>("ParentTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_token_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a00be7-ddff-7598-bfaa-234b454b4029"),
                            ConcurrencyStamp = "7cfd1da2-9854-4677-87ee-b6659ac06491",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("01a00be7-ddff-7598-bfaa-256e7999a546"),
                            ConcurrencyStamp = "57622f33-b382-4978-928e-c7c362208dcc",
                            Name = "Host",
                            NormalizedName = "HOST"
                        },
                        new
                        {
                            Id = new Guid("01a00be7-ddff-7598-bfaa-2b4b9a219feb"),
                            ConcurrencyStamp = "b84be7ca-95b3-464a-9437-f152271e1f2d",
                            Name = "PropertyStaff",
                            NormalizedName = "PROPERTYSTAFF"
                        },
                        new
                        {
                            Id = new Guid("01a00be7-ddff-7598-bfaa-2de215ccf970"),
                            ConcurrencyStamp = "f86f1503-e374-4bb8-9eae-405c9f4e0803",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", "identity");
                });

            modelBuilder.Entity("Promotions.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("discount_value");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<int?>("MaxRedemptions")
                        .HasColumnType("integer")
                        .HasColumnName("max_redemptions");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int>("RedemptionCount")
                        .HasColumnType("integer")
                        .HasColumnName("redemption_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_promotions");

                    b.HasIndex(new[] { "Code" }, "ix_promotions_code")
                        .IsUnique()
                        .HasDatabaseName("ix_promotions_code")
                        .HasFilter("status <> 2");

                    b.HasIndex(new[] { "HostId" }, "ix_promotions_host_id")
                        .HasDatabaseName("ix_promotions_host_id");

                    b.ToTable("promotions", "promotions");
                });

            modelBuilder.Entity("Promotions.Entities.PromotionRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("guest_email");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.Property<DateTimeOffset>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<DateTimeOffset?>("ReversedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reversed_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DiscountAmount", "Promotions.Entities.PromotionRedemption.DiscountAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("discount_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_promotion_redemptions");

                    b.HasIndex(new[] { "BookingId" }, "ix_promotion_redemptions_booking_id")
                        .HasDatabaseName("ix_promotion_redemptions_booking_id");

                    b.HasIndex(new[] { "PromotionId", "GuestEmail" }, "ix_promotion_redemptions_promotion_email")
                        .IsUnique()
                        .HasDatabaseName("ix_promotion_redemptions_promotion_email")
                        .HasFilter("reversed_at IS NULL");

                    b.ToTable("promotion_redemptions", "promotions");
                });

            modelBuilder.Entity("Reviews.Entities.GuestReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("guest_email");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int>("OverallRating")
                        .HasColumnType("integer")
                        .HasColumnName("overall_rating");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_guest_reviews");

                    b.HasIndex(new[] { "BookingId" }, "ix_guest_reviews_booking_id")
                        .IsUnique()
                        .HasDatabaseName("ix_guest_reviews_booking_id");

                    b.HasIndex(new[] { "HostId" }, "ix_guest_reviews_host_id")
                        .HasDatabaseName("ix_guest_reviews_host_id");

                    b.ToTable("guest_reviews", "reviews");
                });

            modelBuilder.Entity("Reviews.Entities.StayReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccuracyRating")
                        .HasColumnType("integer")
                        .HasColumnName("accuracy_rating");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<int>("CleanlinessRating")
                        .HasColumnType("integer")
                        .HasColumnName("cleanliness_rating");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("CommunicationRating")
                        .HasColumnType("integer")
                        .HasColumnName("communication_rating");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<DateTimeOffset?>("HostRepliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("host_replied_at");

                    b.Property<string>("HostReplyText")
                        .HasColumnType("text")
                        .HasColumnName("host_reply_text");

                    b.Property<int>("LocationRating")
                        .HasColumnType("integer")
                        .HasColumnName("location_rating");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<decimal>("OverallRating")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("overall_rating");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<Guid?>("ReviewerCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_customer_id");

                    b.Property<string>("ReviewerGuestEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("reviewer_guest_email");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("ValueRating")
                        .HasColumnType("integer")
                        .HasColumnName("value_rating");

                    b.HasKey("Id")
                        .HasName("pk_stay_reviews");

                    b.HasIndex(new[] { "BookingId" }, "ix_stay_reviews_booking_id")
                        .IsUnique()
                        .HasDatabaseName("ix_stay_reviews_booking_id");

                    b.HasIndex(new[] { "HostId" }, "ix_stay_reviews_host_id")
                        .HasDatabaseName("ix_stay_reviews_host_id");

                    b.HasIndex(new[] { "PropertyId" }, "ix_stay_reviews_property_id")
                        .HasDatabaseName("ix_stay_reviews_property_id");

                    b.ToTable("stay_reviews", "reviews");
                });

            modelBuilder.Entity("Transactions.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("RefundCause")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("refund_cause");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SucceededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("succeeded_at");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transaction_status");

                    b.Property<decimal?>("_refundAmount")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("refund_amount");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "Transactions.Entities.Transaction.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex(new[] { "BookingId" }, "ix_transactions_booking_id")
                        .HasDatabaseName("ix_transactions_booking_id");

                    b.HasIndex(new[] { "BookingId" }, "ix_transactions_booking_id_active")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_booking_id_active")
                        .HasFilter("transaction_status IN ('Pending', 'Succeeded')");

                    b.ToTable("transactions", "transactions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Identity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Identity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Identity.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
