// <auto-generated />
using System;
using System.Collections.Generic;
using Availability;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Availability.Migrations
{
    [DbContext(typeof(AppAvailabilityDbContext))]
    partial class AppAvailabilityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Availability.Entities.UnitAvailabilityHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BookedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<DateTimeOffset?>("HoldExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hold_expires_at");

                    b.Property<string>("HolderToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("holder_token");

                    b.Property<decimal?>("LengthOfStayDiscountAmount")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("length_of_stay_discount_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<NpgsqlRange<DateOnly>>("StayRange")
                        .HasColumnType("daterange")
                        .HasColumnName("stay_range");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPrice", "Availability.Entities.UnitAvailabilityHold.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("total_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_unit_availability_holds");

                    b.HasIndex("HoldExpiresAt")
                        .HasDatabaseName("ix_unit_availability_holds_hold_expires_at")
                        .HasFilter("status = 'held'");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_unit_availability_holds_unit_id");

                    b.HasIndex(new[] { "HolderToken" }, "ix_unit_availability_holds_holder_token_active")
                        .HasDatabaseName("ix_unit_availability_holds_holder_token_active")
                        .HasFilter("status = 'held'");

                    b.HasIndex(new[] { "Status", "BookedAt" }, "ix_unit_availability_holds_status_booked_at")
                        .HasDatabaseName("ix_unit_availability_holds_status_booked_at");

                    b.ToTable("unit_availability_holds", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
