// <auto-generated />
using System;
using System.Collections.Generic;
using Bookings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Bookings.Migrations
{
    [DbContext(typeof(AppBookingsDbContext))]
    [Migration("20260915194518_RemoveBookingsOutbox")]
    partial class RemoveBookingsOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bookings.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("booking_status");

                    b.Property<string>("CancellationPolicy")
                        .HasColumnType("jsonb")
                        .HasColumnName("cancellation_policy");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date")
                        .HasColumnName("check_in");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date")
                        .HasColumnName("check_out");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("guest_email");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("guest_name");

                    b.Property<string>("GuestPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("guest_phone");

                    b.Property<Guid>("HoldId")
                        .HasColumnType("uuid")
                        .HasColumnName("hold_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<DateTimeOffset?>("PaymentDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_due_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<decimal>("_subtotal")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("subtotal");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPrice", "Bookings.Entities.Booking.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("total_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_bookings_customer_id");

                    b.HasIndex("HoldId")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_hold_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_bookings_unit_id");

                    b.HasIndex(new[] { "PaymentDueAt" }, "ix_bookings_payment_due_at_pending")
                        .HasDatabaseName("ix_bookings_payment_due_at")
                        .HasFilter("booking_status = 'Pending' AND payment_due_at IS NOT NULL");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Bookings.Entities.BookingManagementToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_booking_management_tokens");

                    b.HasIndex(new[] { "BookingId" }, "ix_booking_management_tokens_booking_id")
                        .HasDatabaseName("ix_booking_management_tokens_booking_id");

                    b.HasIndex(new[] { "TokenHash" }, "ix_booking_management_tokens_token_hash")
                        .IsUnique()
                        .HasDatabaseName("ix_booking_management_tokens_token_hash");

                    b.ToTable("booking_management_tokens", (string)null);
                });

            modelBuilder.Entity("Bookings.Entities.CheckoutIdempotencyRecord", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("key_hash");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("request_fingerprint");

                    b.HasKey("BookingId")
                        .HasName("pk_checkout_idempotency_records");

                    b.HasIndex(new[] { "CompletedAt" }, "ix_checkout_idempotency_completed_at")
                        .HasDatabaseName("ix_checkout_idempotency_completed_at");

                    b.HasIndex(new[] { "KeyHash" }, "ix_checkout_idempotency_key_hash")
                        .IsUnique()
                        .HasDatabaseName("ix_checkout_idempotency_key_hash");

                    b.ToTable("checkout_idempotency_records", (string)null);
                });

            modelBuilder.Entity("Bookings.Entities.RefundObligation", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cause");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<decimal>("PolicyRefundAmount")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("policy_refund_amount");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("BookingId")
                        .HasName("pk_refund_obligations");

                    b.HasIndex(new[] { "NextAttemptAt" }, "ix_refund_obligations_unresolved")
                        .HasDatabaseName("ix_refund_obligations_unresolved")
                        .HasFilter("resolved_at IS NULL");

                    b.ToTable("refund_obligations", (string)null);
                });

            modelBuilder.Entity("Bookings.Entities.UnitAvailabilityHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BookedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at");

                    b.Property<string>("ClientKey")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("client_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<DateTimeOffset?>("HoldExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hold_expires_at");

                    b.Property<decimal?>("LengthOfStayDiscountAmount")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("length_of_stay_discount_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<NpgsqlRange<DateOnly>>("StayRange")
                        .HasColumnType("daterange")
                        .HasColumnName("stay_range");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPrice", "Bookings.Entities.UnitAvailabilityHold.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("total_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_unit_availability_holds");

                    b.HasIndex("HoldExpiresAt")
                        .HasDatabaseName("ix_unit_availability_holds_hold_expires_at")
                        .HasFilter("status = 'held'");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_unit_availability_holds_unit_id");

                    b.HasIndex(new[] { "ClientKey" }, "ix_unit_availability_holds_client_key_active")
                        .HasDatabaseName("ix_unit_availability_holds_client_key_active")
                        .HasFilter("status IN ('held', 'pending_payment')");

                    b.ToTable("unit_availability_holds", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
