// <auto-generated />
using System;
using System.Collections.Generic;
using Bookings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookings.Migrations
{
    [DbContext(typeof(AppBookingsDbContext))]
    [Migration("20260901013721_AddPendingBookingIntents")]
    partial class AddPendingBookingIntents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bookings.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("booking_status");

                    b.Property<string>("CancellationPolicy")
                        .HasColumnType("jsonb")
                        .HasColumnName("cancellation_policy");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date")
                        .HasColumnName("check_in");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date")
                        .HasColumnName("check_out");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("guest_email");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("guest_name");

                    b.Property<string>("GuestPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("guest_phone");

                    b.Property<Guid>("HoldId")
                        .HasColumnType("uuid")
                        .HasColumnName("hold_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalPrice", "Bookings.Entities.Booking.TotalPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("total_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_bookings_customer_id");

                    b.HasIndex("HoldId")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_hold_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_bookings_unit_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Bookings.Entities.BookingManagementToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_booking_management_tokens");

                    b.HasIndex(new[] { "BookingId" }, "ix_booking_management_tokens_booking_id")
                        .IsUnique()
                        .HasDatabaseName("ix_booking_management_tokens_booking_id");

                    b.HasIndex(new[] { "TokenHash" }, "ix_booking_management_tokens_token_hash")
                        .IsUnique()
                        .HasDatabaseName("ix_booking_management_tokens_token_hash");

                    b.ToTable("booking_management_tokens", (string)null);
                });

            modelBuilder.Entity("Bookings.Entities.PendingBookingIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HoldId")
                        .HasColumnType("uuid")
                        .HasColumnName("hold_id");

                    b.HasKey("Id")
                        .HasName("pk_pending_booking_intents");

                    b.HasIndex(new[] { "CreatedAt" }, "ix_pending_booking_intents_created_at")
                        .HasDatabaseName("ix_pending_booking_intents_created_at");

                    b.HasIndex(new[] { "HoldId" }, "ix_pending_booking_intents_hold_id")
                        .IsUnique()
                        .HasDatabaseName("ix_pending_booking_intents_hold_id");

                    b.ToTable("pending_booking_intents", (string)null);
                });

            modelBuilder.Entity("Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_bookings_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_bookings_outbox_messages_created_at");

                    b.HasIndex("ProcessedAt", "DeadLetteredAt", "NextAttemptAt")
                        .HasDatabaseName("ix_bookings_outbox_messages_processed_at_dead_lettered_at_next");

                    b.ToTable("bookings_outbox_messages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
